# Generated by Django 5.0.6 on 2024-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='gif_url',
        ),
        migrations.AddField(
            model_name='gif',
            name='gif_file',
            field=models.FileField(blank=True, null=True, upload_to='gifs/'),
        ),
    ]
