# Generated by Django 5.0.6 on 2024-07-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0002_remove_gif_gif_url_gif_gif_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gif',
            old_name='descripcion',
            new_name='descripcion_gif',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='descripcion',
            new_name='descripcion_proyecto',
        ),
    ]
