# Generated by Django 5.0.6 on 2024-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_proyecto_dataset_limpio_proyecto_dataset_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='proyectos', to='mycv.skill'),
        ),
    ]
