# Generated by Django 5.0.6 on 2024-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0006_remove_skill_icono_url_skill_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='mycv.skill'),
        ),
    ]
